name: 
on: [push]

jobs:
  deploy:
    name: Compile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/gcloud@master
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
        node-version: '13.x'
      - name: Install EJS Compiler
        run: npm install -g ejs-cli
      - name: Copy files
        run: |
          cp -r img/ ejsout/img
          cp -r js/ ejsout/js
          cp -r scss/ ejsout/scss
					cp -r fonts/ ejsout/fonts
          cp -r vendors/ ejsout/vendors
          cp -r css/ ejsout/css 
          - name: Compile ejs to ejsout
          run: |
          ejs-cli -f index.ejs -o ejsout/
          ejs-cli -f elements/index.ejs -o ejsout/
